// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://butlasgiyjqwazazldue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1dGxhc2dpeWpxd2F6YXpsZHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NTA1MjUsImV4cCI6MjA1MzUyNjUyNX0.K6hTWZWHLtYLgkYdnjFo7hVTaVILQRGECfpg-1acUHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);